modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wum"
version = "${version}"
displayName = "WynnUtilityMod"
authors = "Petrae"
description = '''
Wynn Utility Mod
'''
#logoFile = ""

[[dependencies.wum]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wum]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wum]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.0,)"
ordering = "AFTER"
side = "BOTH"